// ── Core domain types ────────────────────────────────────────────────────
// These match the backend canonical data model (ARCHITECTURE.md §3)

export type Severity = 'critical' | 'warning' | 'info'
export type IncidentStatus = 'active' | 'resolved'

// ── Alert ────────────────────────────────────────────────────────────────
export interface Alert {
  /** UUID */
  id: string
  /** ISO 8601 source timestamp */
  ts: string
  /** Dataset source identifier e.g. "prometheus" | "replay:aiops" | "synthetic" */
  source: string
  host: string | null
  service: string | null
  severity: Severity
  /** Raw alert text */
  message: string
  /** Drain3-extracted parameterized template e.g. "disk full on <HOST>" */
  template: string
  /** Count of identical duplicates collapsed into this row */
  dup_count: number
  /** FK → IncidentCluster.id, null if unclustered / noise */
  cluster_id: string | null
}

// ── Root-cause candidate ──────────────────────────────────────────────────
export interface RootCandidate {
  alert_id: string
  service: string
  template: string
  /** Raw ranking score (sum of weighted signals) */
  score: number
  /** Softmax-normalized confidence 0–1 */
  confidence: number
  is_confirmed?: boolean
}

// ── Incident cluster ──────────────────────────────────────────────────────
export interface Incident {
  /** UUID, stable across updates */
  id: string
  created_at: string
  updated_at: string
  status: IncidentStatus
  /** Short human-readable label generated by LLM/template */
  title: string
  /** Total alert count including dup_count expansions */
  alert_count: number
  /** Unique deduplicated alert count */
  unique_count: number
  /** Services in blast radius */
  services: string[]
  /** Top-3 ranked root-cause candidates */
  root_candidates: RootCandidate[]
  /** Alert-per-tick sparkline data (last N ticks) */
  sparkline: number[]
  /** LLM-generated incident brief, null while generating */
  summary: string | null
  /** LLM-generated first action, null while generating */
  first_action: string | null

  // Custom interactive fields
  acknowledged?: boolean
  acknowledged_by?: string
  resolved_at?: string
  feedback_root_cause?: string
}

// ── Audit Entry ───────────────────────────────────────────────────────────
export interface AuditEntry {
  id: string
  timestamp: string
  type:
    | 'incident_created'
    | 'incident_acknowledged'
    | 'incident_resolved'
    | 'root_cause_confirmed'
    | 'replay_started'
    | 'replay_stopped'
  message: string
  incidentId?: string
}

// ── Topology ──────────────────────────────────────────────────────────────
export interface TopologyNode {
  service: string
  label?: string
}

export interface TopologyEdge {
  source: string
  target: string
}

export interface Topology {
  nodes: TopologyNode[]
  edges: TopologyEdge[]
  /** Services in the propagation path from root cause */
  propagation_path?: string[]
}

// ── Eval results ──────────────────────────────────────────────────────────
export interface EvalScenarioResult {
  scenario: string
  dataset: string
  alert_count: number
  incident_count: number
  compression_ratio: number
  cluster_purity: number
  ari: number
  hit_at_1: number
  hit_at_3: number
  latency_p50_ms: number
  latency_p95_ms: number
}

export interface EvalResults {
  run_at: string
  correlator: string
  embedder: string
  scenarios: EvalScenarioResult[]
}

// ── WebSocket message envelopes (WS_CONTRACT.md) ─────────────────────────

/** alert.batch — raw stream flush every 100ms or 50 alerts */
export interface WsAlertBatch {
  type: 'alert.batch'
  alerts: Alert[]
}

/** alert.dedup — dup_count increment for existing alert, no full re-send */
export interface WsAlertDedup {
  type: 'alert.dedup'
  alert_id: string
  dup_count: number
}

/** incident.created — new cluster with initial member IDs */
export interface WsIncidentCreated {
  type: 'incident.created'
  incident: Incident
  member_alert_ids: string[]
}

/** incident.updated — MUST include added/removed diff for animation layer */
export interface WsIncidentUpdated {
  type: 'incident.updated'
  incident: Incident
  added_alert_ids: string[]
  removed_alert_ids: string[]
}

/** incident.summary — async LLM/template summary arriving after card rendered */
export interface WsIncidentSummary {
  type: 'incident.summary'
  incident_id: string
  title: string
  summary: string
  first_action: string
  generated_by: 'llm' | 'template'
}

/** stats — every 2s, authoritative backend-computed numbers */
export interface WsStats {
  type: 'stats'
  total_alerts: number
  unique_alerts: number
  active_incidents: number
  unclustered: number
  compression_ratio: number
  alerts_per_sec: number
  replay: {
    running: boolean
    dataset: string
    speed: number
    progress: number
  }
}

/** snapshot — sent on (re)connect. Frontend replaces local state. */
export interface WsSnapshot {
  type: 'snapshot'
  incidents: Incident[]
  stats: Omit<WsStats, 'type'>
}

export type WsMessage =
  | WsAlertBatch
  | WsAlertDedup
  | WsIncidentCreated
  | WsIncidentUpdated
  | WsIncidentSummary
  | WsStats
  | WsSnapshot

// ── Replay / demo driver ──────────────────────────────────────────────────
export interface ReplayState {
  status: 'idle' | 'running' | 'paused' | 'done'
  speed: number   // 1× | 5× | 10× | 50× | 100×
  elapsed_alerts: number
  total_alerts: number
}

// ── UI / store helpers ────────────────────────────────────────────────────
export interface LiveStats {
  total_alerts: number
  incident_count: number
  suppression_pct: number   // 0–100
  alerts_per_sec: number
}

/** Per-incident diff record — consumed by the animation layer */
export interface IncidentDiff {
  added_alert_ids: string[]
  removed_alert_ids: string[]
  at: number  // Date.now() when the diff arrived
}
